development:
#  This is for posting to the "api" core
#  solr_core: api_neihardt
#  solr_path: http://server.unl.edu:port/solr/
#  xsl_params:
#    fig_location:
#    file_location: http://server.unl.edu/data/projects/
#    figures: false
#    fw: false
#    pb: false
#    project: neihardt
#    slug: neihardt
#

# This version is for the older non-api neihardt core
  solr_core: nonapi_neihardt
  solr_path: http://server:8983/solr/
  tei_solr_xsl: projects/neihardt/scripts/nonapi_neihardt2solr.xsl
  xsl_params:
    fig_location:
    file_location: http://server.unl.edu/data/projects/
    figures: false
    fw: false
    pb: false
    project: neihardt
    slug: neihardt


production:
  solr_core: neihardt
  xsl_params:
    fig_location: http://server.unl.edu/data_images/projects/example/figures/
    file_location: http://server.unl.edu/data/projects/
    figures: true
    fw: false
    pb: false
    project: neihardt
    slug: neihardt
